In [2]:
import pandas as pd
import numpy as np
import mat73
from matplotlib import pyplot as plt
import scipy.signal as signal

In [3]:
# Import the matlab files
data_dict = mat73.loadmat(r'D:/MarkS3/Documents/Homework/python_hackathon/AllEEG.mat')

In [4]:
# Parse the different fields of the structure
data_dict['AllEEG'].keys()

dict_keys(['AdEEG', 'BDMEEG', 'SubID', 'Triggers'])

In [6]:
# Parse the different fields of the structure
bdm = data_dict['AllEEG'].BDMEEG
ad = data_dict['AllEEG'].AdEEG
subid = data_dict['AllEEG'].SubID
triggers = data_dict['AllEEG'].Triggers

In [18]:
np.shape(bdm[0]['EEG'][0])

(8, 2250)

In [21]:
# Parse BDM data
bdm_eeg = []
bdm_cat = []
bdm_item = []
bdm_label = []
bdm_repitition = []
bdm_sub_id = []
for i in range(len(bdm)):
    sub_id = subid[i]
    for j in range(50):
        bdm_eeg.append(bdm[i]['EEG'][j])
        bdm_cat.append(bdm[i]['Category'][j])
        bdm_item.append(bdm[i]['Item'][j])
        bdm_label.append(bdm[i]['Label'][j])
        bdm_repitition.append(bdm[i]['Repitition'][j])
        bdm_sub_id.append(sub_id)

In [22]:
# Construct BDM Dataframe
colnames = ['sub_id' ,'eeg','category','label','repitition','item']
bdm_df = pd.DataFrame(data=[bdm_sub_id, bdm_eeg, bdm_cat, bdm_label, bdm_repitition, bdm_item],
                     index=colnames).transpose()
bdm_df

,sub_id,eeg,category,label,repitition,item
0,201.0,"[[22.125034535927973, 17.653907708965182, 3.83...",Beverages,80.6,1.0,Neviot
1,201.0,"[[-10.193899819384981, 0.8766877479518658, 0.3...",Hygene,100.0,1.0,Zippersmallbag
2,201.0,"[[-16.752930810400265, -13.97356521714783, -12...",Hygene,100.0,1.0,Sano99
3,201.0,"[[2.929928196900284, -9.54256955794608, -13.21...",Breakfast,70.7,1.0,Branflakesextra
4,201.0,"[[14.294047113047942, 22.568015892354225, 10.6...",DryGoods,100.0,1.0,Prince
...,...,...,...,...,...,...
3595,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",Hygene,39.3,2.0,GelDeLin
3596,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",Hygene,86.7,2.0,Sano99
3597,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",Beverages,84.8,2.0,Neviot
3598,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",Breakfast,17.4,2.0,ChocolateSpread
3599,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",Breakfast,35.2,2.0,Quaker

In [7]:
# Parse Ad data
ad[0].keys()

dict_keys(['AdID', 'Category', 'EEG', 'Item', 'ItemID', 'Label', 'Liking', 'Repitition', 'nArtifacts'])

In [24]:
range(len(ad[0]['EEG']))

range(0, 96)

In [27]:
# Parse Ad data
ad_eeg = []
ad_id = []
ad_cat = []
ad_item = []
ad_label = []
ad_repitition = []
ad_item_id = []
ad_liking = []
ad_sub_id = []
for i in range(len(ad)):
    sub_id = subid[i]
    for j in range(len(ad[i]['EEG'])):
        ad_eeg.append(ad[i]['EEG'][j])
        ad_cat.append(ad[i]['Category'][j])
        ad_item.append(ad[i]['Item'][j])
        ad_label.append(ad[i]['Label'][j])
        ad_repitition.append(ad[i]['Repitition'][j])
        ad_id.append(ad[i]['AdID'][j])
        ad_item_id.append(ad[i]['ItemID'][j])
        ad_liking.append(ad[i]['Liking'][j])
        ad_sub_id.append(sub_id)

In [28]:
# Construct Ad Dataframe
colnames = ['sub_id','eeg','ad_id','category','item','label','repitition','item_id','liking']
ad_df = pd.DataFrame(data=[ad_sub_id, ad_eeg, ad_id, ad_cat, ad_item, ad_label, ad_repitition, ad_item_id, ad_liking],
                     index=colnames).transpose()
ad_df

,sub_id,eeg,ad_id,category,item,label,repitition,item_id,liking
0,201.0,"[[6.169504138131352, 1.4996781805581034, 0.882...",3033.0,DryGoods,Prince,99.5,1.0,303.0,7.0
1,201.0,"[[-9.480992144445933, -10.385721551568722, -8....",1025.0,Breakfast,Branflakesextra,50.8,1.0,102.0,5.0
2,201.0,"[[-29.822218351462798, -22.74021099428629, -19...",5031.0,Snacks,Parachocolate,49.8,1.0,503.0,5.6
3,201.0,"[[19.14256891544619, 21.445438236058163, 11.27...",2052.0,Beverages,Neviot,76.6,1.0,205.0,6.0
4,201.0,"[[2.211251428382117, 4.856250386404814, 6.4057...",3013.0,DryGoods,YadMordechai,78.4,1.0,301.0,6.4
...,...,...,...,...,...,...,...,...,...
6952,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",3045.0,DryGoods,HEINZ,67.8,4.0,304.0,4.0
6953,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",3041.0,DryGoods,HEINZ,69.9,5.0,304.0,4.3
6954,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",5052.0,Snacks,Fitness,65.4,5.0,505.0,1.2
6955,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",2006.0,Beverages,FuzeTeaGreen,75.9,3.0,200.0,4.9
6956,273.0,"[[nan, nan, nan, nan, nan, nan, nan, nan, nan,...",1031.0,Breakfast,ChocolateSpread,15.1,3.0,103.0,2.6